export { default as Header } from './header';
export { default as Card } from './card';
export { default as Loading } from './loading';
export { default as UserDetail } from './userDetail';
export { default as Address } from './adrress';
export { default as Company } from './company';
export { default as Comments } from './comments';
export { default as Comment } from './comment';
export { default as Footer } from './footer';
